import 'package:periodic_table/Elements.dart';
import 'Actinium.dart';
import 'Aluminum.dart';
/**
 * This is the class for generating elements
 */
class ElementFactory {
    /**
     * This method generates the new element
     * @param atomicnum - number of the element
     * @return - returns the new element
     */
    Elements numberfactory(int atomicnum){
        switch (atomicnum){
            default: return null;
            case(1): return new Hydrogen();
            case(2): return new Helium();
            case(3): return new Lithium();
            case(4): return new Beryllium();
            case(5): return new Boron();
            case(6): return new Carbon();
            case(7): return new Nitrogen();
            case(8): return new Oxygen();
            case(9): return new Fluorine();
            case(10): return new Neon();
            case(11): return new Sodium();
            case(12): return new Magnesium();
            case(13): return new Aluminum();
            case(14): return new Silicon();
            case(15): return new Phosphorus();
            case(16): return new Sulfur();
            case(17): return new Chlorine();
            case(18): return new Argon();
            case(19): return new Potassium();
            case(20): return new Calcium();
            case(21): return new Scandium();
            case(22): return new Titanium();
            case(23): return new Vanadium();
            case(24): return new Chromium();
            case(25): return new Manganese();
            case(26): return new Iron();
            case(27): return new Cobalt();
            case(28): return new Nickel();
            case(29): return new Copper();
            case(30): return new Zinc();
            case(31): return new Gallium();
            case(32): return new Germanium();
            case(33): return new Arsenic();
            case(34): return new Selenium();
            case(35): return new Bromine();
            case(36): return new Krypton();
            case(37): return new Rubidium();
            case(38): return new Strontium();
            case(39): return new Yttrium();
            case(40): return new Zirconium();
            case(41): return new Niobium();
            case(42): return new Molybdenum();
            case(43): return new Technetium();
            case(44): return new Ruthenium();
            case(45): return new Rhodium();
            case(46): return new Palladium();
            case(47): return new Silver();
            case(48): return new Cadmium();
            case(49): return new Indium();
            case(50): return new Tin();
            case(51): return new Antimony();
            case(52): return new Tellurium();
            case(53): return new Iodine();
            case(54): return new Xenon();
            case(55): return new Cesium();
            case(56): return new Barium();
            case(57): return new Lanthanum();
            case(58): return new Cerium();
            case(59): return new Praseodymium();
            case(60): return new Neodymium();
            case(61): return new Promethium();
            case(62): return new Samarium();
            case(63): return new Europium();
            case(64): return new Gadolinium();
            case(65): return new Terbium();
            case(66): return new Dysprosium();
            case(67): return new Holmium();
            case(68): return new Erbium();
            case(69): return new Thulium();
            case(70): return new Ytterbium();
            case(71): return new Lutetium();
            case(72): return new Hafnium();
            case(73): return new Tantalum();
            case(74): return new Tungsten();
            case(75): return new Rhenium();
            case(76): return new Osmium();
            case(77): return new Iridium();
            case(78): return new Platinum();
            case(79): return new Gold();
            case(80): return new Mercury();
            case(81): return new Thallium();
            case(82): return new Lead();
            case(83): return new Bismuth();
            case(84): return new Polonium();
            case(85): return new Astatine();
            case(86): return new Radon();
            case(87): return new Francium();
            case(88): return new Radium();
            case(89): return new Actinium();
            case(90): return new Thorium();
            case(91): return new Protactinium();
            case(92): return new Uranium();
            case(93): return new Neptunium();
            case(94): return new Plutonium();
            case(95): return new Americium();
            case(96): return new Curium();
            case(97): return new Berkelium();
            case(98): return new Californium();
            case(99): return new Einsteinium();
            case(100): return new Fermium();
            case(101): return new Mendelevium();
            case(102): return new Nobelium();
            case(103): return new Lawrencium();
            case(104): return new Rutherfordium();
            case(105): return new Dubnium();
            case(106): return new Seaborgium();
            case(107): return new Bohrium();
            case(108): return new Hassium();
            case(109): return new Meitnerium();
            case(110): return new Darmstadtium();
            case(111): return new Roentgenium();
            case(112): return new Copernicium();
            case(113): return new Nihonium();
            case(114): return new Flerovium();
            case(115): return new Moscovium();
            case(116): return new Livermorium();
            case(117): return new Tennessine();
            case(118): return new Oganesson();
        }
    }
    Elements stringfactory(String atomicnum){
        switch (atomicnum){
            default: return null;
            case("Hydrogen"): return new Hydrogen();
            case("Helium"): return new Helium();
            case("Lithium"): return new Lithium();
            case("Beryllium"): return new Beryllium();
            case("Boron"): return new Boron();
            case("Carbon"): return new Carbon();
            case("Nitrogen"): return new Nitrogen();
            case("Oxygen"): return new Oxygen();
            case("Fluorine"): return new Fluorine();
            case("Neon"): return new Neon();
            case("Sodium"): return new Sodium();
            case("Magnesium"): return new Magnesium();
            case("Aluminum"): return new Aluminum();
            case("Silicon"): return new Silicon();
            case("Phosphorus"): return new Phosphorus();
            case("Sulfur"): return new Sulfur();
            case("Chlorine"): return new Chlorine();
            case("Argon"): return new Argon();
            case("Potassium"): return new Potassium();
            case("Calcium"): return new Calcium();
            case("Scandium"): return new Scandium();
            case("Titanium"): return new Titanium();
            case("Vanadium"): return new Vanadium();
            case("Chromium"): return new Chromium();
            case("Manganese"): return new Manganese();
            case("Iron"): return new Iron();
            case("Cobalt"): return new Cobalt();
            case("Nickel"): return new Nickel();
            case("Copper"): return new Copper();
            case("Zinc"): return new Zinc();
            case("Gallium"): return new Gallium();
            case("Germanium"): return new Germanium();
            case("Arsenic"): return new Arsenic();
            case("Selenium"): return new Selenium();
            case("Bromine"): return new Bromine();
            case("Krypton"): return new Krypton();
            case("Rubidium"): return new Rubidium();
            case("Strontium"): return new Strontium();
            case("Yttrium"): return new Yttrium();
            case("Zirconium"): return new Zirconium();
            case("Niobium"): return new Niobium();
            case("Molybdenum"): return new Molybdenum();
            case("Technetium"): return new Technetium();
            case("Ruthenium"): return new Ruthenium();
            case("Rhodium"): return new Rhodium();
            case("Palladium"): return new Palladium();
            case("Silver"): return new Silver();
            case("Cadmium"): return new Cadmium();
            case("Indium"): return new Indium();
            case("Tin"): return new Tin();
            case("Antimony"): return new Antimony();
            case("Tellurium"): return new Tellurium();
            case("Iodine"): return new Iodine();
            case("Xenon"): return new Xenon();
            case("Cesium"): return new Cesium();
            case("Barium"): return new Barium();
            case("Lanthanum"): return new Lanthanum();
            case("Cerium"): return new Cerium();
            case("Praseodymium"): return new Praseodymium();
            case("Neodymium"): return new Neodymium();
            case("Promethium"): return new Promethium();
            case("Samarium"): return new Samarium();
            case("Europium"): return new Europium();
            case("Gadolinium"): return new Gadolinium();
            case("Terbium"): return new Terbium();
            case("Dysprosium"): return new Dysprosium();
            case("Holmium"): return new Holmium();
            case("Erbium"): return new Erbium();
            case("Thulium"): return new Thulium();
            case("Ytterbium"): return new Ytterbium();
            case("Lutetium"): return new Lutetium();
            case("Hafnium"): return new Hafnium();
            case("Tantalum"): return new Tantalum();
            case("Tungsten"): return new Tungsten();
            case("Rhenium"): return new Rhenium();
            case("Osmium"): return new Osmium();
            case("Iridium"): return new Iridium();
            case("Platinum"): return new Platinum();
            case("Gold"): return new Gold();
            case("Mercury"): return new Mercury();
            case("Thallium"): return new Thallium();
            case("Lead"): return new Lead();
            case("Bismuth"): return new Bismuth();
            case("Polonium"): return new Polonium();
            case("Astatine"): return new Astatine();
            case("Radon"): return new Radon();
            case("Francium"): return new Francium();
            case("Radium"): return new Radium();
            case("Actinium"): return new Actinium();
            case("Thorium"): return new Thorium();
            case("Protactinium"): return new Protactinium();
            case("Uranium"): return new Uranium();
            case("Neptunium"): return new Neptunium();
            case("Plutonium"): return new Plutonium();
            case("Americium"): return new Americium();
            case("Curium"): return new Curium();
            case("Berkelium"): return new Berkelium();
            case("Californium"): return new Californium();
            case("Einsteinium"): return new Einsteinium();
            case("Fermium"): return new Fermium();
            case("Mendelevium"): return new Mendelevium();
            case("Nobelium"): return new Nobelium();
            case("Lawrencium"): return new Lawrencium();
            case("Rutherfordium"): return new Rutherfordium();
            case("Dubnium"): return new Dubnium();
            case("Seaborgium"): return new Seaborgium();
            case("Bohrium"): return new Bohrium();
            case("Hassium"): return new Hassium();
            case("Meitnerium"): return new Meitnerium();
            case("Darmstadtium"): return new Darmstadtium();
            case("Roentgenium"): return new Roentgenium();
            case("Copernicium"): return new Copernicium();
            case("Nihonium"): return new Nihonium();
            case("Flerovium"): return new Flerovium();
            case("Moscovium"): return new Moscovium();
            case("Livermorium"): return new Livermorium();
            case("Tennessine"): return new Tennessine();
            case("Oganesson"): return new Oganesson();
        }
    }
    int? checknull(Map<String,int> hash, String shell){
        if(hash.containsKey(shell)){return hash[shell];}
        else return 0;
    }
}
